export const GET_FLIGHTS = "GET_FLIGHTS";
export const GET_FLIGHTS_SUCCESS = "GET_FLIGHTS_SUCCESS";
export const GET_FLIGHTS_ERROR = "GET_FLIGHTS_ERROR";

export const UPDATE_FLIGHTS = 'UPDATE_FLIGHTS';
export const UPDATE_FLIGHTS_SUCCESS = 'UPDATE_FLIGHTS_SUCCESS';
export const UPDATE_FLIGHTS_ERROR = 'UPDATE_FLIGHTS_ERROR';
